### ISSUE TITLE
Unallocated HD Calls - Send internal email auto populates with PB and RC

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#10]
Just to highlight, if you click "Send Internal Email" on an unallocated call "To" it automatically populated with Phil and Rob. It may not be used much but should remove phil.

![image](https://user-images.githubusercontent.com/122997604/220959848-186e6043-393f-4f27-a6ef-f23d14be4b42.png)

**Comment by Belsey23** [comment]
This is driven by the Email Address on the Resource (**Allocated Resource 1**)
