### ISSUE TITLE
Unit Price - Daily Rate not populating

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#11]
I have entered the criteria needed to create a quote on HD0018747 but the "Unit Price - Daily Rate" is not populated.

I also created HD0018746 and created the quote as had not spotted it. The quote "SQ001525" obviously does not have a value. 

![image](https://user-images.githubusercontent.com/122997604/220966481-80d48845-73a2-412e-a004-2b37e5400e7c.png)

**Comment by tscottjendev** [comment]
@JendevSLEG what does the email screen shot have to do with the problem?  Where is the problem?

**Comment by JendevSLEG** [comment]
![image](https://user-images.githubusercontent.com/122997604/221126858-ae82ed69-3c3d-4878-ae60-0edb213fd504.png)

Sorry this is the correct one

**Comment by Belsey23** [comment]
See table 54019 "JI Helpdesk Entry" - GetUnitPrice()

**Comment by tscottjendev** [comment]
@JendevSLEG is 140 the right price for you for training?

**Comment by tscottjendev** [comment]
closed by Jersey-Electricity-plc/JI-InternalSystem-NEW#188 (PR)

**Comment by JendevSLEG** [comment]
Hi Todd,

It is now populating 👍 I'm just going to do a couple of other scenarios to make sure error messages come up if I put in the incorrect "Call Type". 

I'll comment and close if all is ok. 

Thank you

**Comment by JendevSLEG** [comment]
Unit Price - Daily Rate populate as should.
