### ISSUE TITLE
Filter "Resource Capacity" to only show existing staff.

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#15]
There is no filtering option on the "Resource Capacity" page in the new system.

In both the current and new system it brings up a list of existing, x-employees, externals and other resources i.e. ZZ_JE_ITSG.

Is there a way we can add filtering back in with the option to save the view or somehow set it to just show existing resources. It would  make it easier when setting resource capacity in the future. 

In the current system I can filter down the list a bit but cannot save it.

![image](https://user-images.githubusercontent.com/122997604/221544469-f341f52e-2db8-4513-a18f-e05f16f2d678.png)

Any questions please shout.

**Comment by tscottjendev** [comment]
Add filter to page to show only non-blocked resources.  There does not appear to be a way to allow for user filters.

So, if there is a resource you don't want to see, set Blocked on the resource and it will not be displayed.

**Comment by JendevSLEG** [comment]
Thank you @tscottjendev the list is much better 👍 happy to close.
