### ISSUE TITLE
"Resource Time Analysis" Filter list to just existing employees.

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#16]
Sorry, just to see if we can filter the "Resource Time Analysis" list to show existing employees only or have the ability to save the view. Easier for me to view any incomplete days/hours on time sheets and easier for the team to check if they are short or missed a day.

Sorry if I am missing something on the "Options".

**Comment by tscottjendev** [comment]
There is a field on the page you can check to hide blocked resources.  If there are resources you don't want to see block them.

There does not appear to be a way to add user filters to page.

![image](https://user-images.githubusercontent.com/102963427/223126934-ffa904c3-4403-4558-b7aa-da2f20e0f80a.png)

**Comment by JendevSLEG** [comment]
That's perfect thank you @tscottjendev happy to close.
