### ISSUE TITLE
Link Power Bi to BC

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#17]
Just a reminder to investigate how to link BC to the Power Bi report.

**Comment by tscottjendev** [comment]
see Jersey-Electricity-plc/JI-InternalSystem-NEW#205

**Comment by tscottjendev** [comment]
@JendevSLEG  New report at "G:\Jendev General\Jendev Invoicing\Month End SaaS Production.pbix"
