### ISSUE TITLE
Check for errors 

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#18]
Just looking at "Check For Errors" on the time sheets and for BT & TS if J1007 is used and not linked to a HD call it is not bringing in the "Department Code", but for others it has? 

![image](https://user-images.githubusercontent.com/122997604/222407735-f21b6983-3c40-4e9e-884d-c517055ef2e5.png)

One line of BT timesheets is showing up on errors as one of the entries the "Unit Cost" has not been populated.

![image](https://user-images.githubusercontent.com/122997604/222407502-cb129208-1eb4-41ae-99eb-1b7f2a118266.png)

Ben also has one line for MB in his timesheets.

![image](https://user-images.githubusercontent.com/122997604/222408050-b2b068dd-52ea-4250-b1ba-3134420c9988.png)

**Comment by tscottjendev** [comment]
The missing departments were missing in NAV.
The unit cost line is a mystery as the data is correct in NAV.  We will watch.
The MBELSEY in BT's journal is a mystery too.  We will watch.

@JendevSLEG okay to close?

**Comment by JendevSLEG** [comment]
@tscottjendev Happy to close
