### ISSUE TITLE
Check For Errors (Again)

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#19]
I was expecting 4 errors in the time sheets 3 for KB and 1 for TS 

For Todd I was expecting 
Line dated - 14/02/23 (9.15-9.30) as "Work Type" was DEV not Internal for the stand up. 
Instead I have line dated - 15/02/23 (7:30 - 7:45) Department code missing. 

For Kalyanee I was expecting:
Line Dated - 06/02/23 (13.35-14.45) Chargeable was not ticked

Line Dated - 09/02/23 (10:30 - 11:15) Chargeable not ticked
Line Dated - 09/02/23 (15:00 - 16:30) Chargeable not ticked

Instead it shows the below

![image](https://user-images.githubusercontent.com/122997604/222419064-d5c74097-d12f-4fad-b5e3-eacd8367790a.png)

I've only highlighted the time as this does not normally show unless that is all that has been entered.

Please shout if this is as clear as mud.....

**Comment by tscottjendev** [comment]
Todd's Department Code check but not in PBI (same as #19).  
Work Type code not check in Check Errors. Create enhancement issue, please
For KB, Check for Error does not show any errors in NAV.
Chargeable Code not checked in Check Errors.  Create enhancement issue, please.

@JendevSLEG okay to close?

**Comment by JendevSLEG** [comment]
Happy to close. I'll add an enhancement for errors that show in NAV to show in PowerBI and vice versa.
