### ISSUE TITLE
Department Code - for J1007

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#20]
If we use J1007 but it is not linked to a HD call we have to manually enter the "Department Code" this does show when you check for errors but it is not picked up in the Power BI report.

Is this something we can add to Power Bi.

Also is there a way we can have something that reminds the team to enter the "Department Code" if it is not linked to a HD call. It let's me post month end without it.

**Comment by tscottjendev** [comment]
Addressed in #25 and #22
