### ISSUE TITLE
User Setup for NTS_D1\SLEG message when trying to create a quote

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#21]
Trying to create a quote for HD0018781 but the bellow message appears. I have looked at user set up but my user ID is different to everyone else.

Mine is SLEG not NTS_D1\SLEG, apologies if I'm missing something.

![image](https://user-images.githubusercontent.com/122997604/222700958-c68c11ad-8f73-4cb8-8076-1ea99ff7ae5a.png)

**Comment by zwali-je** [comment]
The "User Setup" entry has been modified.

Can you please try again?

Thanks

**Comment by JendevSLEG** [comment]
Hi @zwali-je I'm just going to create a couple more quotes will let you know how it goes. Thank you

**Comment by JendevSLEG** [comment]
@zwali-je Tested - Can now create a quote and attach to a HD call as expected.
