### ISSUE TITLE
Receiving error when viewing/attaching report in a Sales Quote

### ISSUE THREAD

**Issue by zwali-je** [Jersey-Electricity-plc/intsys-issues#24]
Hi @zwali-je I can now create a quote I'll continue testing different scenarios. Once I have created the quote I would Save as PDF, there does not seem to be this option, sorry if it's just me. 

I did find "Attach as PDF" but if I click on this, this message appears.

![image](https://user-images.githubusercontent.com/122997604/223101330-4d135539-b549-4743-bbfb-e19ec5295aa3.png)

In the current system if you "Save as PDF" it saves the quote with the emails.  

Any questions please shout.

_Originally posted by @JendevSLEG in https://github.com/Jersey-Electricity-plc/intsys-issues/issues/21#issuecomment-1455987444_

**Comment by zwali-je** [comment]
Hi @JendevSLEG 

The report layout has been updated now. Can you please test again?

**Comment by JendevSLEG** [comment]
Hi @zwali-je I can now create and view quotes, I have raised another issue "Save as PDF" missing from sales quote". Happy to close this one. Thank yo
