### ISSUE TITLE
"Save as PDF" option missing from sales Quote

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#26]
Once I have created a quote I "Save as PDF" this then saves the PDF's with the emails. 

"Save as PDF" seems to be missing from the sales quote.

**Comment by JendevSLEG** [comment]
Hi @tscottjendev is it the "Attach to Helpdesk call" that I use now?

**Comment by tscottjendev** [comment]
@JendevSLEG yes

**Comment by JendevSLEG** [comment]
@tscottjendev Tested. Saves it to "Attachments" on The HD call which is better especially if there are lots of emails attached. I have shared as email and all looks good.  Happy to close.
