### ISSUE TITLE
Post Timesheets

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#28]
Hello.

Another nice to have, is there a way when I want to post the time sheets I can post the teams all at once? 

At the moment I have to do them separately.

**Comment by tscottjendev** [comment]
@JendevSLEG did you know if you go to Job Journal Templates, Related, Templates, Batches, that there is an action that will post all the batches?

**Comment by JendevSLEG** [comment]
I did not, I'll have a look at this today. Thank you

**Comment by JendevSLEG** [comment]
![image](https://user-images.githubusercontent.com/122997604/225316261-8e795af0-a3d5-4dae-9a68-5533f80e2612.png)

You tried to invoke the Page object with the ID 99000 from the object Job Journal Batches. An object with that ID does not exist in the current application.

Internal session ID: 
828da900-12ae-4596-8bb0-a7bf525e91b4

Application Insights session ID: 
9a1e919f-c652-4413-a16d-18da94cfce57

Client activity id: 
34a251d2-a3aa-4e64-bdc6-e32195b6e9f6

Time stamp on error: 
2023-03-15T12:59:41.8844085Z

**Comment by JendevSLEG** [comment]
![image](https://user-images.githubusercontent.com/122997604/227918852-f3f9d942-82f7-47d5-8aef-875ef0a191f2.png)

**Comment by JendevSLEG** [comment]
> @JendevSLEG did you know if you go to Job Journal Templates, Related, Templates, Batches, that there is an action that will post all the batches?

Did not post everyone timesheets in full i.e. BT, MB & ZW

**Comment by JendevSLEG** [comment]
I've corrected all the errors, as discussed and timesheets have posted. I'll close this one and raise any other issues I come across.
