### ISSUE TITLE
"Recalculate Prices" & "Post" 

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#29]
Would it be possible to promote the "Recalculate Prices" & "Post" options to the main ribbon with "Check for Errors" & "Show All" on the "Timesheet Job Journal" page.

![image](https://user-images.githubusercontent.com/122997604/224070950-40adad02-2cd8-470e-8fc1-517ace9af9db.png)

Another nice to have. Thank you.

**Comment by tscottjendev** [comment]
@JendevSLEG sure but you can personalise that too.

**Comment by JendevSLEG** [comment]
@tscottjendev ah I'll personalise it instead and close this one.

**Comment by JendevSLEG** [comment]
I've moved them and closed this one.
