### ISSUE TITLE
Fixed Price and Time & Materials Reports

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#30]
In the current system when I go to the "Fixed Price & Time and Materials" reports from JE customer page the dates last used are populated. (Helpful if I process month end early) and the customer number is automatically populated with CU00001).

Also "Saved Settings" is not on the page in BC.

Highlighted below from current system.

![image](https://user-images.githubusercontent.com/122997604/224076295-68e9eef0-4ef4-4be8-b3ce-5ac3d1098a82.png)
![image](https://user-images.githubusercontent.com/122997604/224076878-aa4b2e5c-6b17-4d85-9d80-2a8d6afb92de.png)

**Comment by Belsey23** [comment]
I've run both of these from the role centre and it appears to behave as described when re-run

![image](https://user-images.githubusercontent.com/102967931/227232704-d4dac60f-5dbd-4473-bc13-9e377852a5d0.png)

![image](https://user-images.githubusercontent.com/102967931/227232745-3f01b995-e618-4b62-8139-4b8803fdbe3d.png)

**Comment by JendevSLEG** [comment]
Hi @Belsey23 would you have 2 mins re the above?
