### ISSUE TITLE
Permissions issue when posting timesheets

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#31]
When I try and post the timesheets I get the below message.

![image](https://user-images.githubusercontent.com/122997604/224084861-cb50f06a-27c0-4a2b-9774-95f38e0775cc.png)

**Comment by tscottjendev** [comment]
Error details:
Sorry, the current permissions prevented the action. (TableData Job Ledger Entry Modify: Internal System)

To view details about your permissions, see the Effective Permissions page. To report a problem, refer to the following server session ID: '11376'.

Internal session ID: 
76307e5d-235d-4782-8a5e-e5783ee8ca3b

Application Insights session ID: 
dc08b36d-eeaf-4b65-889d-00e3a2096b9f

Client activity id: 
70567bd8-3f48-444c-a3ac-5e64f06fc36d

Time stamp on error: 
2023-03-10T07:57:12.6047791Z

AL call stack: 
"JI Jendev Event Handler"(CodeUnit 54026).Codeunit_JobJnlPostLine_OnAfterRunCode line 18 - Internal System by Jendev
"Job Jnl.-Post Line"(CodeUnit 1012).OnAfterRunCode(Event) line 2 - Base Application by Microsoft
"Job Jnl.-Post Line"(CodeUnit 1012).Code line 75 - Base Application by Microsoft
"Job Jnl.-Post Line"(CodeUnit 1012).RunWithCheck line 7 - Base Application by Microsoft
"Job Jnl.-Post Batch"(CodeUnit 1013).Code line 113 - Base Application by Microsoft
"Job Jnl.-Post Batch"(CodeUnit 1013).OnRun(Trigger) line 4 - Base Application by Microsoft
"Job Jnl.-Post"(CodeUnit 1021).Code line 27 - Base Application by Microsoft
"Job Jnl.-Post"(CodeUnit 1021).OnRun(Trigger) line 3 - Base Application by Microsoft
"JI Timesheet Job Journal"(Page 54015)."Post - OnAction"(Trigger) line 2 - Internal System by Jendev

**Comment by tscottjendev** [comment]
Interestingly, this works on premise.

**Comment by JendevSLEG** [comment]
Tested - Posted Feb timesheets without issue. Happy to close will be retesting when I test the month end process works. I'll log any new issues if needed.
