### ISSUE TITLE
Job Journal Template - Edit List

### ISSUE THREAD

**Issue by Belsey23** [Jersey-Electricity-plc/intsys-issues#34]
![image](https://user-images.githubusercontent.com/122997604/227918852-f3f9d942-82f7-47d5-8aef-875ef0a191f2.png)

_Originally posted by @JendevSLEG in https://github.com/Jersey-Electricity-plc/intsys-issues/issues/28#issuecomment-1484911890_

**Comment by Belsey23** [comment]
![image](https://user-images.githubusercontent.com/102967931/227958620-5705c2a9-b0fc-426e-aa93-94552d9be0b1.png)

**Comment by JendevSLEG** [comment]
Hi @Belsey23 I have tested this and happy to close.
