### ISSUE TITLE
sending internal email from helpdesk call

### ISSUE THREAD

**Issue by shalu231** [Jersey-Electricity-plc/intsys-issues#4]
When picking email addresses, it is limited to contacts only. Could we get a broader list?

**Comment by Belsey23** [comment]
@shalu231 is that From or To Email?
![image](https://user-images.githubusercontent.com/102967931/220894152-6511493e-a98d-4c2f-81d1-9adf57fce592.png)

**Comment by shalu231** [comment]
Hiya!
It is the To Email ...

**Comment by shalu231** [comment]
nope. Checked draft and outbox ...

<img width="656" alt="Capture" src="https://user-images.githubusercontent.com/77927987/220906831-5da6e00b-c24f-4949-8841-ec184c18c536.PNG">

**Comment by Belsey23** [comment]
@tscottjendev any idea about this one?

**Comment by tscottjendev** [comment]
Sorry @shalu231 @Belsey23 what is the issue?  You can put any email in the `To`

**Comment by Belsey23** [comment]
No, that's all good. It's when saving as a draft but doesn't seem to go anywhere

**Comment by tscottjendev** [comment]
Drafts are saved in BC not in your mailbox.  Same with Sent Items.

**Comment by shalu231** [comment]
Thank you Matt 😉

**Comment by tscottjendev** [comment]
Is this closed?
