### ISSUE TITLE
Hours missing from "Fixed Price Adjustment" on "Invoice Details" tab PowerBi

### ISSUE THREAD

**Issue by JendevSLEG** [Jersey-Electricity-plc/intsys-issues#41]
On the "Invoice Details" tab in the SaaS PowerBi it is not bringing in the hours in the "Fixed Price Adjustment" Highlighted below. looking at previous month end documents and current PowerBi it brings in the quoted hours.

![image](https://user-images.githubusercontent.com/122997604/234003773-28efa8d1-73b8-4289-871d-b2836536f81d.png)

It does in the current PowerBi.

**Comment by tscottjendev** [comment]
The hours field in the visual was pulling from the wrong table (Job Journal Line, should be Job Planning Lines).
![image](https://github.com/Jersey-Electricity-plc/intsys-issues/assets/102963427/13772516-a027-4983-ac3d-0168b7b936ff)

**Comment by tscottjendev** [comment]
@JendevSLEG, I have updated the report in g:\Jendev General\Jendev Invoicing.  Let me know if you need anything more.
