### ISSUE TITLE
Email Handling Improvements

### ISSUE THREAD

**Issue by tscottjendev** [Jersey-Electricity-plc/intsys-issues#47]
Some things I don't like about the email handling.

- [x] Too many click to attach and email, especially when there more than the limit set.  Maybe just put a warning in the top of the page and allow the user to load more emails.
- [x] Warn if email already has reference to another email
- [x] Direct way to attach emails to helpdesk call from Timesheet.
- [x] Be nice to be able to open the email listing and then attach emails to tickets to which they apply, rather than having to go to each ticket individually.
- [x] Sort Attached Email by Sent Date (descending)
- [x] Sort Messages by Sent Date (descending)
- [x] Add Action to Set Category and Attach Email
- [x] Add message for emails attached
- [x] Be able to change the source of the messages without leaving the page.
- [x] Show all email related to helpdesk entry from all mail folder **not** just attached

**Comment by Belsey23** [comment]
When clicking **Attach to Helpdesk Entry** there is no confirmation. Not sure if we want a message (e.g. "2 emails attached to HDxxxxxxx") or set a style on the line of emails that are attached?

**Comment by tscottjendev** [comment]
- [ ] Sort Attached Email by Sent Date (descending)
- [ ] Sort Messages by Sent Date (descending)
- [ ] Add Action to Set Category and Attach Email

**Comment by tscottjendev** [comment]
- [ ]  Emails attached and Attachments are separate. Maybe just attach the email to the Document Attachments directly
- [ ]  Can we intercept the Send Internal/External emails and put them in the attached emails without user intervention
- [ ]  Should we attach the release notes email?

**Comment by tscottjendev** [comment]
> When clicking **Attach to Helpdesk Entry** there is no confirmation. Not sure if we want a message (e.g. "2 emails attached to HDxxxxxxx") or set a style on the line of emails that are attached?

Added notifications to address this issue.
