### ISSUE TITLE
Attaching Email to Helpdesk Entry - Sent DateTime

### ISSUE THREAD

**Issue by Belsey23** [Jersey-Electricity-plc/intsys-issues#5]
When pulling in emails from inbox, the Sent DateTime doesn't always display.

Go to Helpdesk Entries > Attached Emails > Inbox > Inbox.

**Screenshots**
![image](https://user-images.githubusercontent.com/102967931/220883843-fdbcafb7-016d-4b42-9582-3ec7e01e0ced.png)

**Comment by tscottjendev** [comment]
Pending publication

**Comment by Belsey23** [comment]
@tscottjendev This is the issue I was referencing, but happy with the solution provided. I will probably just remove the **Created DateTime**.
![image](https://user-images.githubusercontent.com/102967931/232504932-cdad29fe-5c37-40bb-bcb3-b3fe2753113d.png)
