### ISSUE TITLE
Attached Emails - Attach as Category

### ISSUE THREAD

**Issue by Belsey23** [Jersey-Electricity-plc/intsys-issues#54]
When attaching an email it is now a separate action to set the category. This saves times as most emails don't require a category.

Where we have **Attach to Helpdesk Entry** it would be good to have **Attach as Category** which will show the menu of categories to choose from.

![image](https://github.com/Jersey-Electricity-plc/intsys-issues/assets/102967931/d5e38501-b46e-49a0-98c6-6ad781b8f8b3)

**Comment by tscottjendev** [comment]
will do!
