### ISSUE TITLE
Helpdesk Entry > Merge Calls

### ISSUE THREAD

**Issue by Belsey23** [Jersey-Electricity-plc/intsys-issues#7]
Just needs to be tidied up I think:
![image](https://user-images.githubusercontent.com/102967931/220888713-c4fe4ff9-b0f0-4e39-986c-ef6e921a9ef7.png)

![image](https://user-images.githubusercontent.com/102967931/220888806-e5a9910c-cd19-4270-a950-ba0d1596e4da.png)

**Comment by tscottjendev** [comment]
Closed by https://github.com/Jersey-Electricity-plc/JI-InternalSystem-NEW/issues/175
