### ISSUE TITLE
Helpdesk Entry - New Flowfield

### ISSUE THREAD

**Issue by Belsey23** [Jersey-Electricity-plc/intsys-issues#9]
New flowfield "Finished".

The Helpdesk Status record has a boolean field "Finished". Currently XFR, CANCEL and CLOSED are set to "Finished".

I would like to have a flowfield on the Helpdesk Entry record to save filtering Status to **<>CLOSED&<>XFR&<>CANCEL** or **CLOSED|XFR|CANCEL** (am I being a bit lazy? Maybe!)

**Comment by tscottjendev** [comment]
closed by https://github.com/Jersey-Electricity-plc/JI-InternalSystem-NEW/issues/175
